openapi: 3.0.0
info:
  title: Finn API
  version: 1.0.0
paths:
  /expenses:
    get:
      summary: Get all expenses
      responses:
        "200":
          description: A list of expenses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Expense"
    post:
      summary: Create a new expense
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpenseBody"
      responses:
        "201":
          description: The created expense
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
  /expenses/{id}:
    get:
      summary: Get an existing expense
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The existing expense
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
        "404":
          description: Expense not found
    put:
      summary: Update an existing expense
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ExpenseBody"
      responses:
        "200":
          description: The updated expense
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Expense"
        "404":
          description: Expense not found
    delete:
      summary: Delete an existing expense
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Expense deleted
        "404":
          description: Expense not found
  /categories:
    get:
      summary: Get all categories
      responses:
        "200":
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
    ExpenseBody:
      type: object
      properties:
        type:
          type: string
        description:
          type: string
        value:
          type: number
        category_name:
          type: string
    Expense:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        description:
          type: string
        value:
          type: number
        categoryId:
          type: number
        category:
          $ref: "#/components/schemas/Category"
